name: Generate catalog

on:
  # TODO uncomment once we know the scraping works well again
  #schedule:
  #  - cron: 0 5 * * *
  push:
    branches:
      - main

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
        mode: ["scrape", "cleanup"]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      
      - name: deployment
        uses: mamba-org/provision-with-micromamba@main

      - name: generate-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
        run: |
          if [[ "${{ matrix.mode }}" == "scrape" ]]; then
            python scripts/scrape.py
          else
            python scripts/cleanup.py
          fi

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
