name: Generate catalog

on:
  schedule:
    - cron: 0 5 * * 1
  push:
    branches:
      - main
      - dev

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        offset: [0]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4

      - name: deployment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: generate-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
        run: |
          python scripts/generate-catalog.py

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.ref }}

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  cleanup-catalog:
    runs-on: ubuntu-latest
    needs: generate-catalog
    strategy:
      matrix:
        offset: [0]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4

      - name: deployment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: cleanup-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: ${{ matrix.offset }}
        run: |
          python scripts/cleanup-catalog.py

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.ref }}

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
